### PR TITLE
Add tree-sitter-grammars/tree-sitter-tcl to languages

### PR DESCRIPTION
**Pull request by cmosguy**
Hey @grantjenks I just added the TCL language to the py package and it seems to be working pretty well so far.  

Thanks to @simonw  for his contributions in his [Blog post: Using tree-sitter with Python
](https://til.simonwillison.net/python/tree-sitter) helped me understand how to contribute to this.

### CODE REVIEW

**Comment by cmosguy** [comment]
@grantjenks are you able to approve the PR?

**Comment by grantjenks** [comment]
Nope #54

**Comment by Freed-Wu** [comment]
tcl is contained in #53

**Comment by cmosguy** [comment]
@Freed-Wu  I nominate you to take over the repository for @grantjenks since he does not want to do it anymore, what do you think?

So what should I do? Cancel this PR?

**Comment by Freed-Wu** [comment]
If #53 is accepted, this repo will use [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) as an upstream, which any new grammar should be added to upstrem and this repo will update automatically to fetch new grammars by a CI/CD. So this PR should be not needed.

**Comment by cmosguy** [comment]
Thanks @Freed-Wu going to cancel this.  Cheers!

**Pull request closed without merging**
