### PR TITLE
Bump existing grammar versions

### PR DESCRIPTION
**Pull request by tancnle**
- Deprecate support for Python 3.6 and 3.7
- Switch to a maintained fork of `hcl`, `mitchellh/tree-sitter-hcl` -> `MichaHoffmann/tree-sitter-hcl`
- Switch to a maintained fork of `erlang`, `AbstractMachinesLab/tree-sitter-erlang` -> `WhatsApp/tree-sitter-erlang`

### CODE REVIEW

**Comment by tancnle** [comment]
@grantjenks Any thoughts on this PR 🙏🏼?

**Comment by tancnle** [comment]
Interest seg fault with Python 3.6 in the Ubuntu OS 🤔 I wonder if we should drop support for 3.6 and 3.7 since they are already EOF (https://endoflife.date/python)

**Comment by tancnle** [comment]
@grantjenks could you help to kick of the CI build, please? 🙏🏼

**Comment by tancnle** [comment]
@grantjenks This PR is now ready for review 🙏🏼

**Comment by grantjenks** [comment]
Can we keep 3.7 support? Otherwise looks good.

**Comment by tancnle** [comment]
> Can we keep 3.7 support? Otherwise looks good.

Yep. Totally. Addressed in c82123e

**Pull request merged**
