### PR TITLE
tree-sitter-hcl bdc2ee0cbd19d22f8a1529e5c9d099029573c931

### PR DESCRIPTION
**Pull request by dynnamitt**
Added Hashicorp HCL parser into list (alphabetic ordered)

### CODE REVIEW

**Comment by grantjenks** [comment]
There are a couple of other places that need edits like the readme and license list. Check the previous commits for an example.

**Comment by dynnamitt** [comment]
Looking into last commit (RST) I found just one edit into README.rst that I added.
You mentioned "licence list" also ?

**Comment by grantjenks** [comment]
Can you keep the sort order in the readme?

**Comment by dynnamitt** [comment]
> Can you keep the sort order in the readme?

I tried to see if that was the case on others but I could not find a system. What line whould that be?

**Comment by dynnamitt** [comment]
hcl reordered in README now

**Comment by dynnamitt** [comment]
@grantjenks I think the order of url was fixed now

**Comment by grantjenks** [comment]
The readme of the "mitchellh" repo recommends https://github.com/MichaHoffmann/tree-sitter-hcl instead. I'm not sure why this was closed but it's probably worth updating.

**Pull request closed without merging**
