### PR TITLE
Run builds without the upload part on pull request

### PR DESCRIPTION
**Pull request by Akuli**
This should make it much easier to be confident that a pull request is correct.

### CODE REVIEW

**Comment by grantjenks** [comment]
I don’t see why this is necessary. By design, the release workflow doesn’t run on pull requests.

**Comment by Akuli** [comment]
How do you know whether a pull request breaks the build?

**Comment by Akuli** [comment]
This apparently wouldn't make for a great contributing experience anyway, as the build takes about 40 minutes, much longer than I want to wait after making a pull request. Do we still want to run it when a pull request is merged to `main`, so that if a release consists of say 3 new pull requests and the first one is broken, we notice it early instead of when trying to release?

**Comment by grantjenks** [comment]
Oh, usually I have a separate integration workflow. Lgtm

**Comment by grantjenks** [comment]
To the previous comment that I missed:

I don’t think there’s going to be a high merge volume for this repo. And to be honest, I’m not that worried about the build breaking. It’ll only really impact a couple of developers. I didn’t put a ton of thought into the workflow.

**Pull request merged**
